---
# Deployment pour MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  namespace: fleetman
  labels:
    app: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.23
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc

