---
# Deployment pour API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
  namespace: fleetman
  labels:
    app: fleetman-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: supinfo4kube/api-gateway:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production-microservice"
        

