---
# Service pour Web App (NodePort - accès externe)
apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
  namespace: fleetman
  labels:
    app: fleetman-web-app
spec:
  type: NodePort
  selector:
    app: fleetman-web-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http

