---
# Deployment pour Web App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-web-app
  namespace: fleetman
  labels:
    app: fleetman-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-web-app
  template:
    metadata:
      labels:
        app: fleetman-web-app
    spec:
      containers:
      - name: web-app
        image: supinfo4kube/web-app:1.0.0
        ports:
        - containerPort: 80
      #   resources:
      #     requests:
      #       memory: "128Mi"
      #       cpu: "50m"
      #     limits:
      #       memory: "256Mi"
      #       cpu: "200m"
      #   readinessProbe:
      #     httpGet:
      #       path: /
      #       port: 80
      #     initialDelaySeconds: 10
      #     periodSeconds: 5
      #   livenessProbe:
      #     httpGet:
      #       path: /
      #       port: 80
      #     initialDelaySeconds: 30
      #     periodSeconds: 10
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #             - fleetman-web-app
      #         topologyKey: kubernetes.io/hostname

