---
# Deployment pour Web App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-web-app
  namespace: fleetman
  labels:
    app: fleetman-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-web-app
  template:
    metadata:
      labels:
        app: fleetman-web-app
    spec:
      containers:
      - name: web-app
        image: supinfo4kube/web-app:1.0.0
        ports:
        - containerPort: 80
    