
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: default
spec:
  type: ExternalName
  externalName: fleetman-queue.fleetman.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  namespace: default
spec:
  type: ExternalName
  externalName: fleetman-api-gateway.fleetman.svc.cluster.local


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  namespace: default
spec:
  type: ExternalName
  externalName: fleetman-position-tracker.fleetman.svc.cluster.local


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: default
spec:
  type: ExternalName
  externalName: fleetman-position-simulator.fleetman.svc.cluster.local


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  namespace: default
spec:
  type: ExternalName
  externalName: fleetman-mongodb.fleetman.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
  namespace: default
spec:
  type: ExternalName
  externalName: fleetman-web-app.fleetman.svc.cluster.local